In [33]:
import numpy as np

test1 = np.zeros(5) # Создание массива из нулей
test2 = np.ones(5)  # Создание массива из единиц
test3 = np.arange(3) # Создание массива из последовательно идущих 3 натуральных чисел
test4 = np.array([1,2,3]) # Создание массива из списка

print("Создание массивов с использованием функций zeros, ones, arange: \n", test1, test2, test3, "\n")
print("Создание массива из обычного списка: \n", test4, "\n")

print("Вывод формы (shape) и типа данных (dtype) для одного из массивов: \n", np.shape(test4), np.dtype(test4[0]), "\n")

print("Примеры индексирования и срезов: \n", test4[1], test4[0:-1], "\n")

print("Поэлементное умножение массивов: \n", test3 * test4, "\n")
print("Вычисление средней величины: \n", np.mean(test4))

Создание массивов с использованием функций zeros, ones, arange: 
 [0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.] [0 1 2] 

Создание массива из обычного списка: 
 [1 2 3] 

Вывод формы (shape) и типа данных (dtype) для одного из массивов: 
 (3,) int32 

Примеры индексирования и срезов: 
 2 [1 2] 

Поэлементное умножение массивов: 
 [0 2 6] 

Вычисление средней величины: 
 2.0
